[features]
seeds = false
skip-lint = false
[programs.localnet]
pyramid_lottery = "EFSsGtygxE3CoYqrxY9hAJ6nLuL2SNyLnrzLAsyWJo3P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/thename/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
